query_properties = {'joins': {1: {('date_dim', 'store_returns'): [('d_date_sk', 'sr_returned_date_sk')],
               ('store', 'store_returns'): [('s_store_sk', 'sr_store_sk')],
               ('store_returns', 'customer'): [('sr_customer_sk', 'c_customer_sk')]},
           2: {('date_dim', 'date_dim'): [('d_week_seq', 'd_week_seq')]},
           3: {('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
               ('item', 'store_sales'): [('i_item_sk', 'ss_item_sk')]},
           4: {('customer', 'catalog_sales'): [('c_customer_sk', 'cs_bill_customer_sk')],
               ('customer', 'customer'): [('c_customer_id', 'c_customer_id')],
               ('customer', 'store_sales'): [('c_customer_sk', 'ss_customer_sk')],
               ('customer', 'web_sales'): [('c_customer_sk', 'ws_bill_customer_sk')],
               ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
               ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
               ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')]},
           5: {('date_dim', 'store_returns'): [('d_date_sk', 'sr_returned_date_sk')],
               ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
               ('date_dim', 'web_returns'): [('d_date_sk', 'wr_returned_date_sk')],
               ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
               ('web_returns', 'web_sales'): [('wr_order_number', 'ws_order_number'), ('wr_item_sk', 'ws_item_sk')]},
           6: {('customer', 'customer_address'): [('c_current_addr_sk', 'ca_address_sk')],
               ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
               ('item', 'store_sales'): [('i_item_sk', 'ss_item_sk')],
               ('store_sales', 'customer'): [('ss_customer_sk', 'c_customer_sk')]},
           7: {('customer_demographics', 'store_sales'): [('cd_demo_sk', 'ss_cdemo_sk')],
               ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
               ('promotion', 'store_sales'): [('p_promo_sk', 'ss_promo_sk')],
               ('store_sales', 'item'): [('ss_item_sk', 'i_item_sk')]},
           8: {('customer', 'customer_address'): [('c_current_addr_sk', 'ca_address_sk')],
               ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
               ('store_sales', 'store'): [('ss_store_sk', 's_store_sk')]},
           9: {},
           10: {('customer', 'customer_demographics'): [('c_current_cdemo_sk', 'cd_demo_sk')],
                ('customer', 'store_sales'): [('c_customer_sk', 'ss_customer_sk')],
                ('customer', 'web_sales'): [('c_customer_sk', 'ws_bill_customer_sk')],
                ('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')]},
           11: {('customer', 'customer'): [('c_customer_id', 'c_customer_id')],
                ('customer', 'store_sales'): [('c_customer_sk', 'ss_customer_sk')],
                ('customer', 'web_sales'): [('c_customer_sk', 'ws_bill_customer_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')]},
           12: {('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('item', 'web_sales'): [('i_item_sk', 'ws_item_sk')]},
           13: {('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('household_demographics', 'store_sales'): [('hd_demo_sk', 'ss_hdemo_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'customer_address'): [('ss_addr_sk', 'ca_address_sk')],
                ('store_sales', 'customer_demographics'): [('ss_cdemo_sk', 'cd_demo_sk')]},
           14: {('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('item', 'item'): [('i_class_id', 'i_class_id'),
                                   ('i_category_id', 'i_category_id'),
                                   ('i_brand_id', 'i_brand_id')],
                ('item', 'web_sales'): [('i_item_sk', 'ws_item_sk')],
                ('store_sales', 'item'): [('ss_item_sk', 'i_item_sk')]},
           15: {('customer', 'catalog_sales'): [('c_customer_sk', 'cs_bill_customer_sk')],
                ('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')]},
           16: {('call_center', 'catalog_sales'): [('cc_call_center_sk', 'cs_call_center_sk')],
                ('catalog_sales', 'catalog_returns'): [('cs_order_number', 'cr_order_number')],
                ('catalog_sales', 'catalog_sales'): [('cs_order_number', 'cs_order_number')],
                ('customer_address', 'catalog_sales'): [('ca_address_sk', 'cs_ship_addr_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_ship_date_sk')]},
           17: {('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_returns'): [('d_date_sk', 'sr_returned_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_returns', 'catalog_sales'): [('sr_item_sk', 'cs_item_sk'),
                                                     ('sr_customer_sk', 'cs_bill_customer_sk')],
                ('store_sales', 'item'): [('ss_item_sk', 'i_item_sk')],
                ('store_sales', 'store_returns'): [('ss_customer_sk', 'sr_customer_sk'),
                                                   ('ss_item_sk', 'sr_item_sk'),
                                                   ('ss_ticket_number', 'sr_ticket_number')]},
           18: {('catalog_sales', 'item'): [('cs_item_sk', 'i_item_sk')],
                ('customer', 'catalog_sales'): [('c_customer_sk', 'cs_bill_customer_sk')],
                ('customer', 'customer_demographics'): [('c_current_cdemo_sk', 'cd_demo_sk')],
                ('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('customer_demographics', 'catalog_sales'): [('cd_demo_sk', 'cs_bill_cdemo_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')]},
           19: {('customer', 'customer_address'): [('c_current_addr_sk', 'ca_address_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'customer'): [('ss_customer_sk', 'c_customer_sk')],
                ('store_sales', 'store_sales'): [('ss_item_sk', 'ss_item_sk'),
                                                 ('ss_ticket_number', 'ss_ticket_number')]},
           20: {('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('item', 'catalog_sales'): [('i_item_sk', 'cs_item_sk')]},
           21: {('date_dim', 'inventory'): [('d_date_sk', 'inv_date_sk')],
                ('item', 'inventory'): [('i_item_sk', 'inv_item_sk')],
                ('warehouse', 'inventory'): [('w_warehouse_sk', 'inv_warehouse_sk')]},
           22: {('date_dim', 'inventory'): [('d_date_sk', 'inv_date_sk')],
                ('inventory', 'item'): [('inv_item_sk', 'i_item_sk')]},
           23: {('catalog_sales', 'customer'): [('cs_bill_customer_sk', 'c_customer_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('item', 'store_sales'): [('i_item_sk', 'ss_item_sk')],
                ('store_sales', 'customer'): [('ss_customer_sk', 'c_customer_sk')],
                ('web_sales', 'customer'): [('ws_bill_customer_sk', 'c_customer_sk')]},
           24: {('customer', 'customer_address'): [('c_current_addr_sk', 'ca_address_sk')],
                ('customer', 'store_sales'): [('c_customer_sk', 'ss_customer_sk')],
                ('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('customer_address', 'store'): [('ca_zip', 's_zip')],
                ('store', 'customer_address'): [('s_zip', 'ca_zip')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')]},
           25: {('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_returns'): [('d_date_sk', 'sr_returned_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_returns', 'catalog_sales'): [('sr_item_sk', 'cs_item_sk'),
                                                     ('sr_customer_sk', 'cs_bill_customer_sk')],
                ('store_sales', 'item'): [('ss_item_sk', 'i_item_sk')],
                ('store_sales', 'store_returns'): [('ss_customer_sk', 'sr_customer_sk'),
                                                   ('ss_item_sk', 'sr_item_sk'),
                                                   ('ss_ticket_number', 'sr_ticket_number')]},
           26: {('catalog_sales', 'item'): [('cs_item_sk', 'i_item_sk')],
                ('customer_demographics', 'catalog_sales'): [('cd_demo_sk', 'cs_bill_cdemo_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('promotion', 'catalog_sales'): [('p_promo_sk', 'cs_promo_sk')]},
           27: {('customer_demographics', 'store_sales'): [('cd_demo_sk', 'ss_cdemo_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'item'): [('ss_item_sk', 'i_item_sk')]},
           28: {},
           29: {('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_returns'): [('d_date_sk', 'sr_returned_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_returns', 'catalog_sales'): [('sr_item_sk', 'cs_item_sk'),
                                                     ('sr_customer_sk', 'cs_bill_customer_sk')],
                ('store_sales', 'item'): [('ss_item_sk', 'i_item_sk')],
                ('store_sales', 'store_returns'): [('ss_customer_sk', 'sr_customer_sk'),
                                                   ('ss_item_sk', 'sr_item_sk'),
                                                   ('ss_ticket_number', 'sr_ticket_number')]},
           30: {('customer', 'web_returns'): [('c_customer_sk', 'wr_returning_customer_sk')],
                ('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('date_dim', 'web_returns'): [('d_date_sk', 'wr_returned_date_sk')],
                ('web_returns', 'customer_address'): [('wr_returning_addr_sk', 'ca_address_sk')]},
           31: {('customer_address', 'customer_address'): [('ca_county', 'ca_county')],
                ('customer_address', 'store_sales'): [('ca_address_sk', 'ss_addr_sk')],
                ('customer_address', 'web_sales'): [('ca_address_sk', 'ws_bill_addr_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')]},
           32: {('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('item', 'catalog_sales'): [('i_item_sk', 'cs_item_sk')]},
           33: {('catalog_sales', 'item'): [('cs_item_sk', 'i_item_sk')],
                ('customer_address', 'catalog_sales'): [('ca_address_sk', 'cs_bill_addr_sk')],
                ('customer_address', 'store_sales'): [('ca_address_sk', 'ss_addr_sk')],
                ('customer_address', 'web_sales'): [('ca_address_sk', 'ws_bill_addr_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('item', 'item'): [('i_manufact_id', 'i_manufact_id')],
                ('item', 'web_sales'): [('i_item_sk', 'ws_item_sk')],
                ('store_sales', 'item'): [('ss_item_sk', 'i_item_sk')]},
           34: {('customer', 'store_sales'): [('c_customer_sk', 'ss_customer_sk')],
                ('household_demographics', 'store_sales'): [('hd_demo_sk', 'ss_hdemo_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')]},
           35: {('customer', 'customer_demographics'): [('c_current_cdemo_sk', 'cd_demo_sk')],
                ('customer', 'store_sales'): [('c_customer_sk', 'ss_customer_sk')],
                ('customer', 'web_sales'): [('c_customer_sk', 'ws_bill_customer_sk')],
                ('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')]},
           36: {('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'item'): [('ss_item_sk', 'i_item_sk')]},
           37: {('date_dim', 'inventory'): [('d_date_sk', 'inv_date_sk')],
                ('inventory', 'catalog_sales'): [('inv_item_sk', 'cs_item_sk')],
                ('item', 'inventory'): [('i_item_sk', 'inv_item_sk')]},
           38: {('customer', 'catalog_sales'): [('c_customer_sk', 'cs_bill_customer_sk')],
                ('customer', 'customer'): [('c_last_name', 'c_last_name'), ('c_first_name', 'c_first_name')],
                ('customer', 'store_sales'): [('c_customer_sk', 'ss_customer_sk')],
                ('customer', 'web_sales'): [('c_customer_sk', 'ws_bill_customer_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'date_dim'): [('d_date', 'd_date')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')]},
           39: {('date_dim', 'inventory'): [('d_date_sk', 'inv_date_sk')],
                ('item', 'inventory'): [('i_item_sk', 'inv_item_sk')],
                ('item', 'item'): [('i_item_sk', 'i_item_sk')],
                ('warehouse', 'inventory'): [('w_warehouse_sk', 'inv_warehouse_sk')],
                ('warehouse', 'warehouse'): [('w_warehouse_sk', 'w_warehouse_sk')]},
           40: {('catalog_sales', 'catalog_returns'): [('cs_item_sk', 'cr_item_sk'),
                                                       ('cs_order_number', 'cr_order_number')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('item', 'catalog_sales'): [('i_item_sk', 'cs_item_sk')],
                ('warehouse', 'catalog_sales'): [('w_warehouse_sk', 'cs_warehouse_sk')]},
           41: {},
           42: {('store_sales', 'store_sales'): [('ss_item_sk', 'ss_item_sk'),
                                                 ('ss_ticket_number', 'ss_ticket_number')]},
           43: {('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')]},
           44: {},
           45: {('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('web_sales', 'customer'): [('ws_bill_customer_sk', 'c_customer_sk')]},
           46: {('customer', 'store_sales'): [('c_customer_sk', 'ss_customer_sk')],
                ('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('customer_address', 'store_sales'): [('ca_address_sk', 'ss_addr_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('household_demographics', 'store_sales'): [('hd_demo_sk', 'ss_hdemo_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')]},
           47: {('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('item', 'item'): [('i_category', 'i_category'), ('i_brand', 'i_brand')],
                ('item', 'store_sales'): [('i_item_sk', 'ss_item_sk')],
                ('store', 'store'): [('s_company_name', 's_company_name'), ('s_store_name', 's_store_name')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')]},
           48: {('customer_address', 'store_sales'): [('ca_address_sk', 'ss_addr_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'customer_demographics'): [('ss_cdemo_sk', 'cd_demo_sk')]},
           49: {('catalog_returns', 'catalog_sales'): [('cr_order_number', 'cs_order_number'),
                                                       ('cr_item_sk', 'cs_item_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('store_returns', 'store_sales'): [('sr_item_sk', 'ss_item_sk'),
                                                   ('sr_ticket_number', 'ss_ticket_number')],
                ('web_returns', 'web_sales'): [('wr_item_sk', 'ws_item_sk'), ('wr_order_number', 'ws_order_number')]},
           50: {('date_dim', 'store_returns'): [('d_date_sk', 'sr_returned_date_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_returns', 'store_sales'): [('sr_customer_sk', 'ss_customer_sk'),
                                                   ('sr_item_sk', 'ss_item_sk'),
                                                   ('sr_ticket_number', 'ss_ticket_number')],
                ('store_sales', 'date_dim'): [('ss_sold_date_sk', 'd_date_sk')]},
           51: {('date_dim', 'date_dim'): [('d_date', 'd_date')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('web_sales', 'store_sales'): [('ws_item_sk', 'ss_item_sk')]},
           52: {('store_sales', 'store_sales'): [('ss_item_sk', 'ss_item_sk'),
                                                 ('ss_ticket_number', 'ss_ticket_number')]},
           53: {('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'store_sales'): [('ss_item_sk', 'ss_item_sk'),
                                                 ('ss_ticket_number', 'ss_ticket_number')]},
           54: {('customer', 'customer_address'): [('c_current_addr_sk', 'ca_address_sk')],
                ('customer', 'store_sales'): [('c_customer_sk', 'ss_customer_sk')],
                ('store', 'customer_address'): [('s_state', 'ca_state'), ('s_county', 'ca_county')]},
           55: {('store_sales', 'store_sales'): [('ss_item_sk', 'ss_item_sk'),
                                                 ('ss_ticket_number', 'ss_ticket_number')]},
           56: {('customer_address', 'catalog_sales'): [('ca_address_sk', 'cs_bill_addr_sk')],
                ('customer_address', 'store_sales'): [('ca_address_sk', 'ss_addr_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('item', 'catalog_sales'): [('i_item_sk', 'cs_item_sk')],
                ('item', 'item'): [('i_item_id', 'i_item_id')],
                ('item', 'store_sales'): [('i_item_sk', 'ss_item_sk')],
                ('web_sales', 'customer_address'): [('ws_bill_addr_sk', 'ca_address_sk')]},
           57: {('call_center', 'call_center'): [('cc_name', 'cc_name')],
                ('call_center', 'catalog_sales'): [('cc_call_center_sk', 'cs_call_center_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('item', 'catalog_sales'): [('i_item_sk', 'cs_item_sk')],
                ('item', 'item'): [('i_category', 'i_category'), ('i_brand', 'i_brand')]},
           58: {('catalog_sales', 'item'): [('cs_item_sk', 'i_item_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'date_dim'): [('d_date', 'd_date')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('item', 'item'): [('i_item_id', 'i_item_id')],
                ('store_sales', 'item'): [('ss_item_sk', 'i_item_sk')],
                ('web_sales', 'item'): [('ws_item_sk', 'i_item_sk')]},
           59: {('date_dim', 'date_dim'): [('d_week_seq', 'd_week_seq')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('store', 'store'): [('s_store_id', 's_store_id')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')]},
           60: {('customer_address', 'catalog_sales'): [('ca_address_sk', 'cs_bill_addr_sk')],
                ('customer_address', 'store_sales'): [('ca_address_sk', 'ss_addr_sk')],
                ('customer_address', 'web_sales'): [('ca_address_sk', 'ws_bill_addr_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('item', 'catalog_sales'): [('i_item_sk', 'cs_item_sk')],
                ('item', 'item'): [('i_item_id', 'i_item_id')],
                ('item', 'store_sales'): [('i_item_sk', 'ss_item_sk')],
                ('item', 'web_sales'): [('i_item_sk', 'ws_item_sk')]},
           61: {('customer', 'store_sales'): [('c_customer_sk', 'ss_customer_sk')],
                ('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')]},
           62: {('date_dim', 'web_sales'): [('d_date_sk', 'ws_ship_date_sk')],
                ('ship_mode', 'web_sales'): [('sm_ship_mode_sk', 'ws_ship_mode_sk')],
                ('warehouse', 'web_sales'): [('w_warehouse_sk', 'ws_warehouse_sk')],
                ('web_site', 'web_sales'): [('web_site_sk', 'ws_web_site_sk')]},
           63: {('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'store_sales'): [('ss_item_sk', 'ss_item_sk'),
                                                 ('ss_ticket_number', 'ss_ticket_number')]},
           64: {('catalog_returns', 'catalog_sales'): [('cr_order_number', 'cs_order_number'),
                                                       ('cr_item_sk', 'cs_item_sk')],
                ('catalog_sales', 'item'): [('cs_item_sk', 'i_item_sk')],
                ('customer', 'customer_address'): [('c_current_addr_sk', 'ca_address_sk')],
                ('customer', 'customer_demographics'): [('c_current_cdemo_sk', 'cd_demo_sk')],
                ('customer', 'date_dim'): [('c_first_shipto_date_sk', 'd_date_sk'),
                                           ('c_first_sales_date_sk', 'd_date_sk')],
                ('customer', 'household_demographics'): [('c_current_hdemo_sk', 'hd_demo_sk')],
                ('income_band', 'household_demographics'): [('ib_income_band_sk', 'hd_income_band_sk')],
                ('item', 'item'): [('i_item_sk', 'i_item_sk')],
                ('item', 'store_returns'): [('i_item_sk', 'sr_item_sk')],
                ('promotion', 'store_sales'): [('p_promo_sk', 'ss_promo_sk')],
                ('store', 'store'): [('s_zip', 's_zip'), ('s_store_name', 's_store_name')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'customer'): [('ss_customer_sk', 'c_customer_sk')],
                ('store_sales', 'customer_address'): [('ss_addr_sk', 'ca_address_sk')],
                ('store_sales', 'customer_demographics'): [('ss_cdemo_sk', 'cd_demo_sk')],
                ('store_sales', 'household_demographics'): [('ss_hdemo_sk', 'hd_demo_sk')],
                ('store_sales', 'store_returns'): [('ss_ticket_number', 'sr_ticket_number')],
                ('store_sales', 'store_sales'): [('ss_item_sk', 'ss_item_sk'),
                                                 ('ss_ticket_number', 'ss_ticket_number')]},
           65: {('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'item'): [('ss_item_sk', 'i_item_sk')]},
           66: {('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('ship_mode', 'catalog_sales'): [('sm_ship_mode_sk', 'cs_ship_mode_sk')],
                ('time_dim', 'catalog_sales'): [('t_time_sk', 'cs_sold_time_sk')],
                ('time_dim', 'web_sales'): [('t_time_sk', 'ws_sold_time_sk')],
                ('warehouse', 'catalog_sales'): [('w_warehouse_sk', 'cs_warehouse_sk')],
                ('warehouse', 'web_sales'): [('w_warehouse_sk', 'ws_warehouse_sk')]},
           67: {('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('item', 'store_sales'): [('i_item_sk', 'ss_item_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')]},
           68: {('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('customer_address', 'store_sales'): [('ca_address_sk', 'ss_addr_sk')],
                ('household_demographics', 'store_sales'): [('hd_demo_sk', 'ss_hdemo_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'customer'): [('ss_customer_sk', 'c_customer_sk')]},
           69: {('customer', 'catalog_sales'): [('c_customer_sk', 'cs_ship_customer_sk')],
                ('customer', 'customer_demographics'): [('c_current_cdemo_sk', 'cd_demo_sk')],
                ('customer', 'store_sales'): [('c_customer_sk', 'ss_customer_sk')],
                ('customer', 'web_sales'): [('c_customer_sk', 'ws_bill_customer_sk')],
                ('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')]},
           70: {('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('store', 'store'): [('s_state', 's_state')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')]},
           71: {('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')]},
           72: {('catalog_sales', 'customer_demographics'): [('cs_bill_cdemo_sk', 'cd_demo_sk')],
                ('catalog_sales', 'date_dim'): [('cs_ship_date_sk', 'd_date_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'date_dim'): [('d_week_seq', 'd_week_seq')],
                ('date_dim', 'inventory'): [('d_date_sk', 'inv_date_sk')],
                ('household_demographics', 'catalog_sales'): [('hd_demo_sk', 'cs_bill_hdemo_sk')],
                ('inventory', 'catalog_sales'): [('inv_item_sk', 'cs_item_sk')],
                ('inventory', 'item'): [('inv_item_sk', 'i_item_sk')],
                ('promotion', 'catalog_sales'): [('p_promo_sk', 'cs_promo_sk')],
                ('warehouse', 'inventory'): [('w_warehouse_sk', 'inv_warehouse_sk')]},
           73: {('household_demographics', 'store_sales'): [('hd_demo_sk', 'ss_hdemo_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'customer'): [('ss_customer_sk', 'c_customer_sk')]},
           74: {('customer', 'customer'): [('c_customer_id', 'c_customer_id')],
                ('customer', 'store_sales'): [('c_customer_sk', 'ss_customer_sk')],
                ('customer', 'web_sales'): [('c_customer_sk', 'ws_bill_customer_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')]},
           75: {('catalog_returns', 'catalog_sales'): [('cr_order_number', 'cs_order_number'),
                                                       ('cr_item_sk', 'cs_item_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('item', 'catalog_sales'): [('i_item_sk', 'cs_item_sk')],
                ('item', 'store_sales'): [('i_item_sk', 'ss_item_sk')],
                ('store_returns', 'store_sales'): [('sr_item_sk', 'ss_item_sk'),
                                                   ('sr_ticket_number', 'ss_ticket_number')],
                ('web_sales', 'web_returns'): [('ws_order_number', 'wr_order_number'), ('ws_item_sk', 'wr_item_sk')]},
           76: {('catalog_sales', 'date_dim'): [('cs_sold_date_sk', 'd_date_sk')],
                ('catalog_sales', 'item'): [('cs_item_sk', 'i_item_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('item', 'store_sales'): [('i_item_sk', 'ss_item_sk')],
                ('web_sales', 'date_dim'): [('ws_sold_date_sk', 'd_date_sk')],
                ('web_sales', 'item'): [('ws_item_sk', 'i_item_sk')]},
           77: {('date_dim', 'catalog_returns'): [('d_date_sk', 'cr_returned_date_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_returns'): [('d_date_sk', 'sr_returned_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_returns'): [('d_date_sk', 'wr_returned_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')]},
           78: {('catalog_returns', 'catalog_sales'): [('cr_order_number', 'cs_order_number'),
                                                       ('cr_item_sk', 'cs_item_sk')],
                ('catalog_sales', 'store_sales'): [('cs_item_sk', 'ss_item_sk'),
                                                   ('cs_bill_customer_sk', 'ss_customer_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('store_returns', 'store_sales'): [('sr_item_sk', 'ss_item_sk'),
                                                   ('sr_ticket_number', 'ss_ticket_number')],
                ('web_returns', 'web_sales'): [('wr_item_sk', 'ws_item_sk'), ('wr_order_number', 'ws_order_number')],
                ('web_sales', 'store_sales'): [('ws_item_sk', 'ss_item_sk'),
                                               ('ws_bill_customer_sk', 'ss_customer_sk')]},
           79: {('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('household_demographics', 'store_sales'): [('hd_demo_sk', 'ss_hdemo_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'customer'): [('ss_customer_sk', 'c_customer_sk')]},
           80: {('catalog_sales', 'catalog_page'): [('cs_catalog_page_sk', 'cp_catalog_page_sk')],
                ('catalog_sales', 'catalog_returns'): [('cs_item_sk', 'cr_item_sk'),
                                                       ('cs_order_number', 'cr_order_number')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('item', 'catalog_sales'): [('i_item_sk', 'cs_item_sk')],
                ('promotion', 'catalog_sales'): [('p_promo_sk', 'cs_promo_sk')],
                ('promotion', 'store_sales'): [('p_promo_sk', 'ss_promo_sk')],
                ('promotion', 'web_sales'): [('p_promo_sk', 'ws_promo_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'store_returns'): [('ss_item_sk', 'sr_item_sk'),
                                                   ('ss_ticket_number', 'sr_ticket_number')],
                ('store_sales', 'store_sales'): [('ss_item_sk', 'ss_item_sk'),
                                                 ('ss_ticket_number', 'ss_ticket_number')],
                ('web_sales', 'web_returns'): [('ws_item_sk', 'wr_item_sk'), ('ws_order_number', 'wr_order_number')],
                ('web_site', 'web_sales'): [('web_site_sk', 'ws_web_site_sk')]},
           81: {('catalog_returns', 'customer_address'): [('cr_returning_addr_sk', 'ca_address_sk')],
                ('customer', 'catalog_returns'): [('c_customer_sk', 'cr_returning_customer_sk')],
                ('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('date_dim', 'catalog_returns'): [('d_date_sk', 'cr_returned_date_sk')]},
           82: {('date_dim', 'inventory'): [('d_date_sk', 'inv_date_sk')],
                ('item', 'inventory'): [('i_item_sk', 'inv_item_sk')],
                ('item', 'store_sales'): [('i_item_sk', 'ss_item_sk')]},
           83: {('catalog_returns', 'item'): [('cr_item_sk', 'i_item_sk')],
                ('date_dim', 'catalog_returns'): [('d_date_sk', 'cr_returned_date_sk')],
                ('date_dim', 'date_dim'): [('d_date', 'd_date'), ('d_week_seq', 'd_week_seq')],
                ('date_dim', 'store_returns'): [('d_date_sk', 'sr_returned_date_sk')],
                ('date_dim', 'web_returns'): [('d_date_sk', 'wr_returned_date_sk')],
                ('item', 'item'): [('i_item_id', 'i_item_id')],
                ('store_returns', 'item'): [('sr_item_sk', 'i_item_sk')],
                ('web_returns', 'item'): [('wr_item_sk', 'i_item_sk')]},
           84: {('customer', 'customer_demographics'): [('c_current_cdemo_sk', 'cd_demo_sk')],
                ('customer', 'household_demographics'): [('c_current_hdemo_sk', 'hd_demo_sk')],
                ('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('customer_demographics', 'store_returns'): [('cd_demo_sk', 'sr_cdemo_sk')],
                ('income_band', 'household_demographics'): [('ib_income_band_sk', 'hd_income_band_sk')]},
           85: {('customer_demographics', 'customer_demographics'): [('cd_education_status', 'cd_education_status'),
                                                                     ('cd_marital_status', 'cd_marital_status')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('reason', 'web_returns'): [('r_reason_sk', 'wr_reason_sk')],
                ('web_page', 'web_sales'): [('wp_web_page_sk', 'ws_web_page_sk')],
                ('web_returns', 'customer_address'): [('wr_refunded_addr_sk', 'ca_address_sk')],
                ('web_returns', 'customer_demographics'): [('wr_returning_cdemo_sk', 'cd_demo_sk'),
                                                           ('wr_refunded_cdemo_sk', 'cd_demo_sk')],
                ('web_sales', 'web_returns'): [('ws_item_sk', 'wr_item_sk'), ('ws_order_number', 'wr_order_number')]},
           86: {('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('web_sales', 'item'): [('ws_item_sk', 'i_item_sk')]},
           87: {('customer', 'catalog_sales'): [('c_customer_sk', 'cs_bill_customer_sk')],
                ('customer', 'customer'): [('c_last_name', 'c_last_name'), ('c_first_name', 'c_first_name')],
                ('customer', 'store_sales'): [('c_customer_sk', 'ss_customer_sk')],
                ('customer', 'web_sales'): [('c_customer_sk', 'ws_bill_customer_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'date_dim'): [('d_date', 'd_date')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')]},
           88: {('household_demographics', 'store_sales'): [('hd_demo_sk', 'ss_hdemo_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('time_dim', 'store_sales'): [('t_time_sk', 'ss_sold_time_sk')]},
           89: {('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('store_sales', 'store_sales'): [('ss_item_sk', 'ss_item_sk'),
                                                 ('ss_ticket_number', 'ss_ticket_number')]},
           90: {('household_demographics', 'web_sales'): [('hd_demo_sk', 'ws_ship_hdemo_sk')],
                ('web_page', 'web_sales'): [('wp_web_page_sk', 'ws_web_page_sk')],
                ('web_sales', 'time_dim'): [('ws_sold_time_sk', 't_time_sk')]},
           91: {('call_center', 'catalog_returns'): [('cc_call_center_sk', 'cr_call_center_sk')],
                ('customer', 'catalog_returns'): [('c_customer_sk', 'cr_returning_customer_sk')],
                ('customer', 'customer_demographics'): [('c_current_cdemo_sk', 'cd_demo_sk')],
                ('customer_address', 'customer'): [('ca_address_sk', 'c_current_addr_sk')],
                ('date_dim', 'catalog_returns'): [('d_date_sk', 'cr_returned_date_sk')],
                ('household_demographics', 'customer'): [('hd_demo_sk', 'c_current_hdemo_sk')]},
           92: {('date_dim', 'web_sales'): [('d_date_sk', 'ws_sold_date_sk')],
                ('item', 'web_sales'): [('i_item_sk', 'ws_item_sk')]},
           93: {('reason', 'store_returns'): [('r_reason_sk', 'sr_reason_sk')],
                ('store_returns', 'store_sales'): [('sr_item_sk', 'ss_item_sk'),
                                                   ('sr_ticket_number', 'ss_ticket_number')]},
           94: {('customer_address', 'web_sales'): [('ca_address_sk', 'ws_ship_addr_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_ship_date_sk')],
                ('web_sales', 'web_returns'): [('ws_order_number', 'wr_order_number')],
                ('web_sales', 'web_sales'): [('ws_order_number', 'ws_order_number')],
                ('web_site', 'web_sales'): [('web_site_sk', 'ws_web_site_sk')]},
           95: {('customer_address', 'web_sales'): [('ca_address_sk', 'ws_ship_addr_sk')],
                ('date_dim', 'web_sales'): [('d_date_sk', 'ws_ship_date_sk')],
                ('web_returns', 'web_sales'): [('wr_order_number', 'ws_order_number')],
                ('web_sales', 'web_returns'): [('ws_order_number', 'wr_order_number')],
                ('web_sales', 'web_sales'): [('ws_order_number', 'ws_order_number')],
                ('web_site', 'web_sales'): [('web_site_sk', 'ws_web_site_sk')]},
           96: {('household_demographics', 'store_sales'): [('hd_demo_sk', 'ss_hdemo_sk')],
                ('store', 'store_sales'): [('s_store_sk', 'ss_store_sk')],
                ('time_dim', 'store_sales'): [('t_time_sk', 'ss_sold_time_sk')]},
           97: {('catalog_sales', 'store_sales'): [('cs_item_sk', 'ss_item_sk'),
                                                   ('cs_bill_customer_sk', 'ss_customer_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_sold_date_sk')],
                ('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')]},
           98: {('date_dim', 'store_sales'): [('d_date_sk', 'ss_sold_date_sk')],
                ('store_sales', 'item'): [('ss_item_sk', 'i_item_sk')]},
           99: {('call_center', 'catalog_sales'): [('cc_call_center_sk', 'cs_call_center_sk')],
                ('date_dim', 'catalog_sales'): [('d_date_sk', 'cs_ship_date_sk')],
                ('ship_mode', 'catalog_sales'): [('sm_ship_mode_sk', 'cs_ship_mode_sk')],
                ('warehouse', 'catalog_sales'): [('w_warehouse_sk', 'cs_warehouse_sk')]}},
 'payload': {1: {'customer': {'c_customer_id': 'OB'},
                 'date_dim': {'d_year': 'EQ'},
                 'store': {'s_state': 'EQ'},
                 'store_returns': {'sr_customer_sk': 'GB', 'sr_return_amt': 'PL', 'sr_store_sk': 'IS NOT'}},
             2: {'catalog_sales': {'cs_ext_sales_price': 'PL', 'cs_sold_date_sk': 'PL'},
                 'date_dim': {'d_date_sk': 'GB', 'd_day_name': 'PL', 'd_week_seq': 'OB', 'd_year': 'EQ'},
                 'web_sales': {'ws_ext_sales_price': 'PL', 'ws_sold_date_sk': 'PL'}},
             3: {'date_dim': {'d_moy': 'EQ', 'd_year': 'GB'},
                 'item': {'i_brand': 'GB', 'i_brand_id': 'GB', 'i_manufact_id': 'EQ'}},
             4: {'catalog_sales': {'cs_ext_discount_amt': 'PL',
                                   'cs_ext_list_price': 'PL',
                                   'cs_ext_sales_price': 'PL',
                                   'cs_ext_wholesale_cost': 'PL'},
                 'customer': {'c_birth_country': 'GB',
                              'c_customer_id': 'GB',
                              'c_email_address': 'GB',
                              'c_first_name': 'GB',
                              'c_last_name': 'GB',
                              'c_login': 'GB',
                              'c_preferred_cust_flag': 'GB'},
                 'date_dim': {'d_year': 'EQ'},
                 'store_sales': {'ss_ext_discount_amt': 'PL',
                                 'ss_ext_list_price': 'PL',
                                 'ss_ext_sales_price': 'PL',
                                 'ss_ext_wholesale_cost': 'PL'},
                 'web_sales': {'ws_ext_discount_amt': 'PL',
                               'ws_ext_list_price': 'PL',
                               'ws_ext_sales_price': 'PL',
                               'ws_ext_wholesale_cost': 'PL'}},
             5: {'catalog_page': {'cp_catalog_page_id': 'PL', 'cp_catalog_page_sk': 'PL'},
                 'catalog_returns': {'cr_catalog_page_sk': 'PL',
                                     'cr_net_loss': 'PL',
                                     'cr_return_amount': 'PL',
                                     'cr_returned_date_sk': 'PL'},
                 'catalog_sales': {'cs_catalog_page_sk': 'PL',
                                   'cs_ext_sales_price': 'PL',
                                   'cs_net_profit': 'PL',
                                   'cs_sold_date_sk': 'PL'},
                 'store': {'s_store_id': 'GB', 's_store_sk': 'PL'},
                 'store_returns': {'sr_net_loss': 'PL', 'sr_return_amt': 'PL', 'sr_store_sk': 'PL'},
                 'store_sales': {'ss_ext_sales_price': 'PL', 'ss_net_profit': 'PL', 'ss_store_sk': 'PL'},
                 'web_returns': {'wr_net_loss': 'PL', 'wr_return_amt': 'PL'},
                 'web_sales': {'ws_ext_sales_price': 'PL', 'ws_net_profit': 'PL', 'ws_web_site_sk': 'PL'},
                 'web_site': {'web_site_id': 'GB', 'web_site_sk': 'PL'}},
             6: {'customer_address': {'ca_state': 'GB'},
                 'date_dim': {'d_month_seq': 'PL', 'd_moy': 'EQ', 'd_year': 'EQ'},
                 'item': {'i_category': 'IS NOT', 'i_current_price': 'GT'}},
             7: {'customer_demographics': {'cd_education_status': 'EQ', 'cd_gender': 'EQ', 'cd_marital_status': 'EQ'},
                 'date_dim': {'d_year': 'EQ'},
                 'item': {'i_item_id': 'GB'},
                 'promotion': {'p_channel_email': 'EQ', 'p_channel_event': 'EQ'},
                 'store_sales': {'ss_coupon_amt': 'PL',
                                 'ss_list_price': 'PL',
                                 'ss_quantity': 'PL',
                                 'ss_sales_price': 'PL'}},
             8: {'customer': {'c_preferred_cust_flag': 'EQ'},
                 'customer_address': {'ca_zip': 'PL'},
                 'date_dim': {'d_qoy': 'EQ', 'd_year': 'EQ'},
                 'store': {'s_store_name': 'GB', 's_zip': 'PL'},
                 'store_sales': {'ss_net_profit': 'PL'}},
             9: {'store_sales': {'ss_ext_tax': 'PL', 'ss_net_paid_inc_tax': 'PL', 'ss_quantity': 'GE'}},
             10: {'catalog_sales': {'cs_ship_customer_sk': 'PL'},
                  'customer': {'c_customer_sk': 'OB'},
                  'customer_address': {'ca_county': 'EQ'},
                  'customer_demographics': {'cd_credit_rating': 'GB',
                                            'cd_dep_college_count': 'GB',
                                            'cd_dep_count': 'GB',
                                            'cd_dep_employed_count': 'GB',
                                            'cd_education_status': 'GB',
                                            'cd_gender': 'GB',
                                            'cd_marital_status': 'GB',
                                            'cd_purchase_estimate': 'GB'},
                  'date_dim': {'d_moy': 'GE', 'd_year': 'EQ'}},
             11: {'customer': {'c_birth_country': 'GB',
                               'c_customer_id': 'GB',
                               'c_email_address': 'GB',
                               'c_first_name': 'GB',
                               'c_last_name': 'GB',
                               'c_login': 'GB',
                               'c_preferred_cust_flag': 'GB'},
                  'date_dim': {'d_year': 'EQ'},
                  'store_sales': {'ss_ext_discount_amt': 'PL', 'ss_ext_list_price': 'PL'},
                  'web_sales': {'ws_ext_discount_amt': 'PL', 'ws_ext_list_price': 'PL'}},
             12: {'item': {'i_category': 'EQ',
                           'i_class': 'GB',
                           'i_current_price': 'GB',
                           'i_item_desc': 'GB',
                           'i_item_id': 'GB'},
                  'web_sales': {'ws_ext_sales_price': 'PL'}},
             13: {'customer_address': {'ca_country': 'EQ', 'ca_state': 'EQ'},
                  'customer_demographics': {'cd_education_status': 'EQ', 'cd_marital_status': 'EQ'},
                  'date_dim': {'d_year': 'EQ'},
                  'household_demographics': {'hd_dep_count': 'EQ'},
                  'store_sales': {'ss_cdemo_sk': 'GB',
                                  'ss_ext_sales_price': 'PL',
                                  'ss_ext_wholesale_cost': 'PL',
                                  'ss_net_profit': 'GE',
                                  'ss_quantity': 'PL',
                                  'ss_sales_price': 'GE'}},
             14: {'catalog_sales': {'cs_list_price': 'PL', 'cs_quantity': 'PL'},
                  'date_dim': {'d_moy': 'EQ', 'd_year': 'GE'},
                  'item': {'i_brand_id': 'GB', 'i_category_id': 'GB', 'i_class_id': 'GB'},
                  'store_sales': {'ss_list_price': 'PL', 'ss_quantity': 'PL'},
                  'web_sales': {'ws_list_price': 'PL', 'ws_quantity': 'PL'}},
             15: {'catalog_sales': {'cs_sales_price': 'PL'},
                  'customer_address': {'ca_state': 'PL', 'ca_zip': 'OB'},
                  'date_dim': {'d_qoy': 'EQ', 'd_year': 'EQ'}},
             16: {'call_center': {'cc_county': 'EQ'},
                  'catalog_sales': {'cs_ext_ship_cost': 'PL',
                                    'cs_net_profit': 'PL',
                                    'cs_order_number': 'GB',
                                    'cs_warehouse_sk': 'PL'},
                  'customer_address': {'ca_state': 'EQ'}},
             17: {'catalog_sales': {'cs_quantity': 'PL'},
                  'date_dim': {'d_quarter_name': 'EQ'},
                  'item': {'i_item_desc': 'GB', 'i_item_id': 'GB'},
                  'store': {'s_state': 'GB'},
                  'store_returns': {'sr_return_quantity': 'PL'},
                  'store_sales': {'ss_item_sk': 'GB', 'ss_quantity': 'PL'}},
             18: {'catalog_sales': {'cs_coupon_amt': 'PL',
                                    'cs_list_price': 'PL',
                                    'cs_net_profit': 'PL',
                                    'cs_quantity': 'PL',
                                    'cs_sales_price': 'PL'},
                  'customer': {'c_birth_month': 'EQ', 'c_birth_year': 'PL'},
                  'customer_address': {'ca_country': 'GB', 'ca_county': 'GB', 'ca_state': 'EQ'},
                  'customer_demographics': {'cd_dep_count': 'PL', 'cd_education_status': 'EQ', 'cd_gender': 'EQ'},
                  'date_dim': {'d_year': 'EQ'},
                  'item': {'i_item_id': 'GB'}},
             19: {'customer_address': {'ca_zip': 'PL'},
                  'date_dim': {'d_date_sk': 'PL', 'd_moy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_brand': 'GB',
                           'i_brand_id': 'GB',
                           'i_item_sk': 'PL',
                           'i_manager_id': 'EQ',
                           'i_manufact': 'GB',
                           'i_manufact_id': 'GB'},
                  'store': {'s_zip': 'PL'}},
             20: {'catalog_sales': {'cs_ext_sales_price': 'PL'},
                  'item': {'i_category': 'EQ',
                           'i_class': 'GB',
                           'i_current_price': 'GB',
                           'i_item_desc': 'GB',
                           'i_item_id': 'GB'}},
             21: {'inventory': {'inv_quantity_on_hand': 'PL'},
                  'item': {'i_current_price': 'GE', 'i_item_id': 'GB'},
                  'warehouse': {'w_warehouse_name': 'GB'}},
             22: {'date_dim': {'d_month_seq': 'GE'},
                  'inventory': {'inv_quantity_on_hand': 'PL'},
                  'item': {'i_brand': 'GB', 'i_category': 'GB', 'i_class': 'GB', 'i_product_name': 'GB'}},
             23: {'date_dim': {'d_moy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_item_desc': 'PL', 'i_item_sk': 'GB'},
                  'store_sales': {'ss_quantity': 'PL', 'ss_sales_price': 'PL'}},
             24: {'customer': {'c_birth_country': 'PL', 'c_first_name': 'GB', 'c_last_name': 'GB'},
                  'customer_address': {'ca_country': 'PL', 'ca_state': 'GB'},
                  'item': {'i_color': 'EQ',
                           'i_current_price': 'GB',
                           'i_item_sk': 'PL',
                           'i_manager_id': 'GB',
                           'i_size': 'GB',
                           'i_units': 'GB'},
                  'store': {'s_market_id': 'EQ', 's_state': 'GB', 's_store_name': 'GB'},
                  'store_sales': {'ss_item_sk': 'PL', 'ss_net_paid_inc_tax': 'PL', 'ss_ticket_number': 'PL'}},
             25: {'catalog_sales': {'cs_net_profit': 'PL'},
                  'date_dim': {'d_moy': 'GE', 'd_year': 'EQ'},
                  'item': {'i_item_desc': 'GB', 'i_item_id': 'GB'},
                  'store': {'s_store_id': 'GB', 's_store_name': 'GB'},
                  'store_returns': {'sr_net_loss': 'PL'},
                  'store_sales': {'ss_item_sk': 'GB', 'ss_net_profit': 'PL'}},
             26: {'catalog_sales': {'cs_coupon_amt': 'PL',
                                    'cs_list_price': 'PL',
                                    'cs_quantity': 'PL',
                                    'cs_sales_price': 'PL'},
                  'customer_demographics': {'cd_education_status': 'EQ', 'cd_gender': 'EQ', 'cd_marital_status': 'EQ'},
                  'date_dim': {'d_year': 'EQ'},
                  'item': {'i_item_id': 'GB'},
                  'promotion': {'p_channel_email': 'EQ', 'p_channel_event': 'EQ'}},
             27: {'customer_demographics': {'cd_education_status': 'EQ', 'cd_gender': 'EQ', 'cd_marital_status': 'EQ'},
                  'date_dim': {'d_year': 'EQ'},
                  'item': {'i_item_id': 'GB'},
                  'store': {'s_state': 'EQ'},
                  'store_sales': {'ss_coupon_amt': 'PL',
                                  'ss_list_price': 'PL',
                                  'ss_quantity': 'PL',
                                  'ss_sales_price': 'PL'}},
             28: {'store_sales': {'ss_coupon_amt': 'GE',
                                  'ss_list_price': 'GE',
                                  'ss_quantity': 'GE',
                                  'ss_wholesale_cost': 'GE'}},
             29: {'catalog_sales': {'cs_quantity': 'PL'},
                  'date_dim': {'d_moy': 'GE', 'd_year': 'EQ'},
                  'item': {'i_item_desc': 'GB', 'i_item_id': 'GB'},
                  'store': {'s_store_id': 'GB', 's_store_name': 'GB'},
                  'store_returns': {'sr_return_quantity': 'PL'},
                  'store_sales': {'ss_item_sk': 'GB', 'ss_quantity': 'PL'}},
             30: {'customer': {'c_birth_country': 'OB',
                               'c_birth_day': 'OB',
                               'c_birth_month': 'OB',
                               'c_birth_year': 'OB',
                               'c_customer_id': 'OB',
                               'c_email_address': 'OB',
                               'c_first_name': 'OB',
                               'c_last_name': 'OB',
                               'c_last_review_date': 'OB',
                               'c_login': 'OB',
                               'c_preferred_cust_flag': 'OB',
                               'c_salutation': 'OB'},
                  'customer_address': {'ca_state': 'EQ'},
                  'date_dim': {'d_year': 'EQ'},
                  'web_returns': {'wr_return_amt': 'PL', 'wr_returning_customer_sk': 'GB'}},
             31: {'date_dim': {'d_qoy': 'EQ', 'd_year': 'EQ'}, 'web_sales': {'ws_ext_sales_price': 'PL'}},
             32: {'catalog_sales': {'cs_ext_discount_amt': 'GT', 'cs_item_sk': 'GB'}, 'item': {'i_manufact_id': 'EQ'}},
             33: {'catalog_sales': {'cs_ext_sales_price': 'PL'},
                  'customer_address': {'ca_gmt_offset': 'EQ'},
                  'date_dim': {'d_moy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_category': 'EQ', 'i_manufact_id': 'GB'},
                  'web_sales': {'ws_ext_sales_price': 'PL'}},
             34: {'customer': {'c_first_name': 'OB',
                               'c_last_name': 'OB',
                               'c_preferred_cust_flag': 'OB',
                               'c_salutation': 'OB'},
                  'date_dim': {'d_date_sk': 'PL', 'd_dom': 'GE', 'd_year': 'EQ'},
                  'household_demographics': {'hd_buy_potential': 'EQ', 'hd_dep_count': 'GT', 'hd_vehicle_count': 'GT'},
                  'store': {'s_county': 'EQ'},
                  'store_sales': {'ss_ticket_number': 'OB'}},
             35: {'catalog_sales': {'cs_ship_customer_sk': 'PL'},
                  'customer_address': {'ca_state': 'GB'},
                  'customer_demographics': {'cd_dep_college_count': 'GB',
                                            'cd_dep_count': 'GB',
                                            'cd_dep_employed_count': 'GB',
                                            'cd_gender': 'GB',
                                            'cd_marital_status': 'GB'},
                  'date_dim': {'d_qoy': 'LT', 'd_year': 'EQ'}},
             36: {'date_dim': {'d_year': 'EQ'},
                  'item': {'i_category': 'GB', 'i_class': 'GB'},
                  'store': {'s_state': 'EQ'},
                  'store_sales': {'ss_ext_sales_price': 'PL', 'ss_net_profit': 'PL'}},
             37: {'inventory': {'inv_item_sk': 'OB', 'inv_quantity_on_hand': 'GE'},
                  'item': {'i_current_price': 'GE', 'i_item_desc': 'OB', 'i_item_id': 'OB', 'i_manufact_id': 'EQ'}},
             38: {'customer': {'c_first_name': 'OB', 'c_last_name': 'OB'},
                  'date_dim': {'d_date': 'OB', 'd_month_seq': 'GE'},
                  'web_sales': {'ws_item_sk': 'OB', 'ws_order_number': 'OB'}},
             39: {'date_dim': {'d_moy': 'EQ', 'd_year': 'EQ'},
                  'inventory': {'inv_quantity_on_hand': 'PL'},
                  'item': {'i_item_sk': 'OB'},
                  'warehouse': {'w_warehouse_sk': 'OB'}},
             40: {'catalog_returns': {'cr_refunded_cash': 'PL'},
                  'catalog_sales': {'cs_sales_price': 'PL'},
                  'item': {'i_current_price': 'GE', 'i_item_id': 'OB'},
                  'warehouse': {'w_state': 'OB'}},
             41: {'item': {'i_category': 'EQ',
                           'i_color': 'EQ',
                           'i_manufact': 'EQ',
                           'i_manufact_id': 'GE',
                           'i_product_name': 'GB',
                           'i_size': 'EQ',
                           'i_units': 'EQ'}},
             42: {'date_dim': {'d_date_sk': 'PL', 'd_moy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_category': 'OB', 'i_category_id': 'OB', 'i_item_sk': 'PL', 'i_manager_id': 'EQ'}},
             43: {'date_dim': {'d_day_name': 'PL', 'd_year': 'EQ'},
                  'store': {'s_gmt_offset': 'EQ', 's_store_id': 'GB', 's_store_name': 'GB'},
                  'store_sales': {'ss_sales_price': 'PL'}},
             44: {'store_sales': {'ss_customer_sk': 'IS', 'ss_item_sk': 'GB', 'ss_store_sk': 'EQ'}},
             45: {'customer_address': {'ca_city': 'GB', 'ca_zip': 'EQ'},
                  'date_dim': {'d_qoy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_item_id': 'EQ'},
                  'web_sales': {'ws_item_sk': 'PL', 'ws_sales_price': 'PL'}},
             46: {'customer': {'c_first_name': 'OB', 'c_last_name': 'OB'},
                  'customer_address': {'ca_city': 'OB'},
                  'date_dim': {'d_dow': 'EQ', 'd_year': 'EQ'},
                  'household_demographics': {'hd_dep_count': 'EQ', 'hd_vehicle_count': 'EQ'},
                  'store': {'s_city': 'EQ'},
                  'store_sales': {'ss_coupon_amt': 'PL', 'ss_net_profit': 'PL', 'ss_ticket_number': 'OB'}},
             47: {'date_dim': {'d_moy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_brand': 'GB', 'i_category': 'GB'},
                  'store': {'s_company_name': 'GB', 's_store_name': 'GB'},
                  'store_sales': {'ss_sales_price': 'PL'}},
             48: {'customer_address': {'ca_country': 'EQ', 'ca_state': 'EQ'},
                  'customer_demographics': {'cd_education_status': 'EQ', 'cd_marital_status': 'EQ'},
                  'date_dim': {'d_year': 'EQ'},
                  'store_sales': {'ss_net_profit': 'GE', 'ss_quantity': 'PL', 'ss_sales_price': 'GE'}},
             49: {'catalog_returns': {'cr_return_amount': 'GT', 'cr_return_quantity': 'PL'},
                  'catalog_sales': {'cs_item_sk': 'GB',
                                    'cs_net_paid': 'GT',
                                    'cs_net_profit': 'GT',
                                    'cs_quantity': 'GT'},
                  'date_dim': {'d_moy': 'EQ', 'd_year': 'EQ'},
                  'store_returns': {'sr_return_amt': 'GT', 'sr_return_quantity': 'PL'},
                  'store_sales': {'ss_item_sk': 'GB', 'ss_net_paid': 'GT', 'ss_net_profit': 'GT', 'ss_quantity': 'GT'},
                  'web_returns': {'wr_return_amt': 'GT', 'wr_return_quantity': 'PL'},
                  'web_sales': {'ws_item_sk': 'GB', 'ws_net_paid': 'GT', 'ws_net_profit': 'GT', 'ws_quantity': 'GT'}},
             50: {'date_dim': {'d_moy': 'EQ', 'd_year': 'EQ'},
                  'store': {'s_city': 'GB',
                            's_company_id': 'GB',
                            's_county': 'GB',
                            's_state': 'GB',
                            's_store_name': 'GB',
                            's_street_name': 'GB',
                            's_street_number': 'GB',
                            's_street_type': 'GB',
                            's_suite_number': 'GB',
                            's_zip': 'GB'}},
             51: {'date_dim': {'d_date': 'GB', 'd_month_seq': 'GE'},
                  'store_sales': {'ss_item_sk': 'OB', 'ss_sales_price': 'PL'},
                  'web_sales': {'ws_item_sk': 'GB', 'ws_sales_price': 'PL'}},
             52: {'date_dim': {'d_date_sk': 'PL', 'd_moy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_brand': 'PL', 'i_brand_id': 'OB', 'i_item_sk': 'PL', 'i_manager_id': 'EQ'}},
             53: {'date_dim': {'d_date_sk': 'PL', 'd_month_seq': 'EQ', 'd_qoy': 'GB'},
                  'item': {'i_brand': 'EQ',
                           'i_category': 'EQ',
                           'i_class': 'EQ',
                           'i_item_sk': 'PL',
                           'i_manufact_id': 'GB'}},
             54: {'customer': {'c_customer_sk': 'GB'},
                  'date_dim': {'d_date_sk': 'PL', 'd_month_seq': 'GE', 'd_moy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_category': 'EQ', 'i_class': 'EQ', 'i_item_sk': 'PL'}},
             55: {'date_dim': {'d_date_sk': 'PL', 'd_moy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_brand': 'GB', 'i_brand_id': 'GB', 'i_item_sk': 'PL', 'i_manager_id': 'EQ'}},
             56: {'catalog_sales': {'cs_ext_sales_price': 'PL'},
                  'customer_address': {'ca_gmt_offset': 'EQ'},
                  'date_dim': {'d_moy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_color': 'EQ', 'i_item_id': 'GB'}},
             57: {'call_center': {'cc_name': 'GB'},
                  'catalog_sales': {'cs_sales_price': 'PL'},
                  'date_dim': {'d_moy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_brand': 'GB', 'i_category': 'GB'}},
             58: {'catalog_sales': {'cs_ext_sales_price': 'PL'}, 'item': {'i_item_id': 'GB'}},
             59: {'date_dim': {'d_date_sk': 'GB', 'd_day_name': 'PL', 'd_month_seq': 'GE', 'd_week_seq': 'OB'},
                  'store': {'s_store_id': 'OB', 's_store_name': 'OB', 's_store_sk': 'GB'},
                  'store_sales': {'ss_sales_price': 'PL', 'ss_store_sk': 'GB'}},
             60: {'catalog_sales': {'cs_ext_sales_price': 'PL'},
                  'customer_address': {'ca_gmt_offset': 'EQ'},
                  'date_dim': {'d_moy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_category': 'EQ', 'i_item_id': 'GB'},
                  'web_sales': {'ws_ext_sales_price': 'PL'}},
             61: {'customer_address': {'ca_gmt_offset': 'EQ'},
                  'date_dim': {'d_date_sk': 'PL', 'd_moy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_category': 'EQ', 'i_item_sk': 'PL'},
                  'promotion': {'p_channel_dmail': 'EQ',
                                'p_channel_email': 'EQ',
                                'p_channel_tv': 'EQ',
                                'p_promo_sk': 'OB'},
                  'store': {'s_gmt_offset': 'EQ'},
                  'store_sales': {'ss_item_sk': 'OB', 'ss_promo_sk': 'OB'}},
             62: {'date_dim': {'d_month_seq': 'GE'},
                  'ship_mode': {'sm_type': 'GB'},
                  'warehouse': {'w_warehouse_name': 'PL'},
                  'web_sales': {'ws_sold_date_sk': 'PL'},
                  'web_site': {'web_name': 'GB'}},
             63: {'date_dim': {'d_date_sk': 'PL', 'd_month_seq': 'EQ', 'd_moy': 'GB'},
                  'item': {'i_brand': 'EQ',
                           'i_category': 'EQ',
                           'i_class': 'EQ',
                           'i_item_sk': 'PL',
                           'i_manager_id': 'GB'}},
             64: {'catalog_returns': {'cr_refunded_cash': 'PL', 'cr_reversed_charge': 'PL', 'cr_store_credit': 'PL'},
                  'catalog_sales': {'cs_ext_list_price': 'PL'},
                  'customer_address': {'ca_city': 'GB',
                                       'ca_street_name': 'GB',
                                       'ca_street_number': 'GB',
                                       'ca_zip': 'GB'},
                  'customer_demographics': {'cd_marital_status': 'PL'},
                  'date_dim': {'d_year': 'EQ'},
                  'item': {'i_color': 'EQ', 'i_current_price': 'GE', 'i_item_sk': 'GB', 'i_product_name': 'OB'},
                  'store': {'s_store_name': 'GB', 's_zip': 'GB'}},
             65: {'date_dim': {'d_month_seq': 'GE'},
                  'item': {'i_brand': 'PL', 'i_current_price': 'PL', 'i_item_desc': 'OB', 'i_wholesale_cost': 'PL'},
                  'store': {'s_store_name': 'OB'},
                  'store_sales': {'ss_sales_price': 'PL', 'ss_store_sk': 'IS NOT'}},
             66: {'catalog_sales': {'cs_ext_list_price': 'PL', 'cs_net_paid_inc_tax': 'PL', 'cs_quantity': 'PL'},
                  'date_dim': {'d_moy': 'PL', 'd_year': 'EQ'},
                  'ship_mode': {'sm_carrier': 'EQ'},
                  'time_dim': {'t_time': 'GE'},
                  'warehouse': {'w_city': 'GB',
                                'w_country': 'GB',
                                'w_county': 'GB',
                                'w_state': 'GB',
                                'w_warehouse_name': 'GB',
                                'w_warehouse_sq_ft': 'GB'}},
             67: {'date_dim': {'d_month_seq': 'GE', 'd_moy': 'GB', 'd_qoy': 'GB', 'd_year': 'GB'},
                  'item': {'i_brand': 'GB', 'i_category': 'GB', 'i_class': 'GB', 'i_product_name': 'GB'},
                  'store': {'s_store_id': 'GB'},
                  'store_sales': {'ss_quantity': 'PL', 'ss_sales_price': 'PL'}},
             68: {'customer': {'c_first_name': 'PL', 'c_last_name': 'OB'},
                  'date_dim': {'d_date_sk': 'PL', 'd_dom': 'GE', 'd_year': 'EQ'},
                  'household_demographics': {'hd_dep_count': 'EQ', 'hd_vehicle_count': 'EQ'},
                  'store': {'s_city': 'EQ'},
                  'store_sales': {'ss_ticket_number': 'OB'}},
             69: {'customer_address': {'ca_state': 'EQ'},
                  'customer_demographics': {'cd_credit_rating': 'GB',
                                            'cd_education_status': 'GB',
                                            'cd_gender': 'GB',
                                            'cd_marital_status': 'GB',
                                            'cd_purchase_estimate': 'GB'},
                  'date_dim': {'d_moy': 'GE', 'd_year': 'EQ'}},
             70: {'date_dim': {'d_month_seq': 'GE'},
                  'store': {'s_county': 'GB', 's_state': 'GB'},
                  'store_sales': {'ss_net_profit': 'PL'}},
             71: {'catalog_sales': {'cs_ext_sales_price': 'PL', 'cs_item_sk': 'PL', 'cs_sold_time_sk': 'PL'},
                  'date_dim': {'d_moy': 'EQ', 'd_year': 'EQ'},
                  'item': {'i_brand': 'GB', 'i_brand_id': 'GB', 'i_item_sk': 'PL', 'i_manager_id': 'EQ'},
                  'store_sales': {'ss_ext_sales_price': 'PL', 'ss_item_sk': 'PL', 'ss_sold_time_sk': 'PL'},
                  'time_dim': {'t_hour': 'GB', 't_meal_time': 'EQ', 't_minute': 'GB', 't_time_sk': 'PL'},
                  'web_sales': {'ws_ext_sales_price': 'PL', 'ws_item_sk': 'PL', 'ws_sold_time_sk': 'PL'}},
             72: {'catalog_sales': {'cs_quantity': 'PL'},
                  'customer_demographics': {'cd_marital_status': 'EQ'},
                  'date_dim': {'d_week_seq': 'GB', 'd_year': 'EQ'},
                  'inventory': {'inv_quantity_on_hand': 'PL'},
                  'item': {'i_item_desc': 'GB'},
                  'warehouse': {'w_warehouse_name': 'GB'}},
             73: {'customer': {'c_first_name': 'PL',
                               'c_last_name': 'OB',
                               'c_preferred_cust_flag': 'PL',
                               'c_salutation': 'PL'},
                  'date_dim': {'d_date_sk': 'PL', 'd_dom': 'GE', 'd_year': 'EQ'},
                  'household_demographics': {'hd_buy_potential': 'EQ', 'hd_dep_count': 'GT', 'hd_vehicle_count': 'GT'},
                  'store': {'s_county': 'EQ'}},
             74: {'customer': {'c_customer_id': 'OB', 'c_first_name': 'OB', 'c_last_name': 'OB'},
                  'date_dim': {'d_year': 'EQ'},
                  'store_sales': {'ss_net_paid': 'PL'},
                  'web_sales': {'ws_net_paid': 'PL'}},
             75: {'catalog_returns': {'cr_return_amount': 'PL', 'cr_return_quantity': 'PL'},
                  'catalog_sales': {'cs_ext_sales_price': 'PL', 'cs_quantity': 'PL'},
                  'date_dim': {'d_year': 'EQ'},
                  'item': {'i_brand_id': 'PL',
                           'i_category': 'EQ',
                           'i_category_id': 'PL',
                           'i_class_id': 'PL',
                           'i_manufact_id': 'PL'},
                  'store_returns': {'sr_return_amt': 'PL', 'sr_return_quantity': 'PL'},
                  'store_sales': {'ss_ext_sales_price': 'PL', 'ss_quantity': 'PL'},
                  'web_returns': {'wr_return_amt': 'PL', 'wr_return_quantity': 'PL'}},
             76: {'catalog_sales': {'cs_ext_sales_price': 'OB', 'cs_ship_addr_sk': 'IS'},
                  'date_dim': {'d_qoy': 'OB', 'd_year': 'OB'},
                  'item': {'i_category': 'OB'},
                  'store_sales': {'ss_ext_sales_price': 'OB', 'ss_promo_sk': 'IS'},
                  'web_sales': {'ws_ext_sales_price': 'OB', 'ws_promo_sk': 'IS'}},
             77: {'catalog_returns': {'cr_call_center_sk': 'PL', 'cr_net_loss': 'PL', 'cr_return_amount': 'PL'},
                  'catalog_sales': {'cs_call_center_sk': 'GB', 'cs_ext_sales_price': 'PL', 'cs_net_profit': 'PL'},
                  'store': {'s_store_sk': 'GB'},
                  'store_returns': {'sr_net_loss': 'PL', 'sr_return_amt': 'PL', 'sr_store_sk': 'GB'},
                  'store_sales': {'ss_ext_sales_price': 'PL', 'ss_net_profit': 'PL', 'ss_store_sk': 'GB'},
                  'web_page': {'wp_web_page_sk': 'GB'},
                  'web_returns': {'wr_net_loss': 'PL', 'wr_return_amt': 'PL', 'wr_web_page_sk': 'GB'},
                  'web_sales': {'ws_ext_sales_price': 'PL', 'ws_net_profit': 'PL', 'ws_web_page_sk': 'GB'}},
             78: {'catalog_returns': {'cr_order_number': 'IS'},
                  'catalog_sales': {'cs_quantity': 'PL', 'cs_sales_price': 'PL', 'cs_wholesale_cost': 'PL'},
                  'date_dim': {'d_year': 'EQ'},
                  'store_returns': {'sr_ticket_number': 'IS'},
                  'store_sales': {'ss_customer_sk': 'OB',
                                  'ss_item_sk': 'OB',
                                  'ss_quantity': 'PL',
                                  'ss_sales_price': 'PL',
                                  'ss_wholesale_cost': 'PL'},
                  'web_returns': {'wr_order_number': 'IS'},
                  'web_sales': {'ws_quantity': 'PL', 'ws_sales_price': 'PL', 'ws_wholesale_cost': 'PL'}},
             79: {'customer': {'c_first_name': 'OB', 'c_last_name': 'OB'},
                  'date_dim': {'d_dow': 'EQ', 'd_year': 'EQ'},
                  'household_demographics': {'hd_dep_count': 'EQ', 'hd_vehicle_count': 'GT'},
                  'store': {'s_city': 'PL', 's_number_employees': 'GE'},
                  'store_sales': {'ss_addr_sk': 'PL',
                                  'ss_coupon_amt': 'PL',
                                  'ss_net_profit': 'PL',
                                  'ss_ticket_number': 'PL'}},
             80: {'catalog_page': {'cp_catalog_page_id': 'PL'},
                  'catalog_returns': {'cr_net_loss': 'PL', 'cr_return_amount': 'PL'},
                  'catalog_sales': {'cs_ext_sales_price': 'PL', 'cs_net_profit': 'PL'},
                  'item': {'i_current_price': 'GT'},
                  'promotion': {'p_channel_tv': 'EQ'},
                  'store': {'s_store_id': 'GB'},
                  'store_returns': {'sr_net_loss': 'PL', 'sr_return_amt': 'PL'},
                  'web_returns': {'wr_net_loss': 'PL', 'wr_return_amt': 'PL'},
                  'web_site': {'web_site_id': 'GB'}},
             81: {'catalog_returns': {'cr_return_amt_inc_tax': 'PL', 'cr_returning_customer_sk': 'GB'},
                  'customer': {'c_customer_id': 'OB', 'c_first_name': 'OB', 'c_last_name': 'OB', 'c_salutation': 'OB'},
                  'customer_address': {'ca_city': 'OB',
                                       'ca_country': 'OB',
                                       'ca_county': 'OB',
                                       'ca_gmt_offset': 'OB',
                                       'ca_location_type': 'OB',
                                       'ca_state': 'EQ',
                                       'ca_street_name': 'OB',
                                       'ca_street_number': 'OB',
                                       'ca_street_type': 'OB',
                                       'ca_suite_number': 'OB',
                                       'ca_zip': 'OB'},
                  'date_dim': {'d_year': 'EQ'}},
             82: {'inventory': {'inv_quantity_on_hand': 'GE'},
                  'item': {'i_current_price': 'GE',
                           'i_item_desc': 'GB',
                           'i_item_id': 'GB',
                           'i_item_sk': 'GB',
                           'i_manufact_id': 'EQ'}},
             83: {'catalog_returns': {'cr_item_sk': 'GB', 'cr_order_number': 'GB', 'cr_return_quantity': 'PL'},
                  'item': {'i_item_id': 'GB'},
                  'store_returns': {'sr_return_quantity': 'PL'},
                  'web_returns': {'wr_return_quantity': 'PL'}},
             84: {'customer': {'c_customer_id': 'OB', 'c_first_name': 'PL', 'c_last_name': 'PL'},
                  'income_band': {'ib_lower_bound': 'GE', 'ib_upper_bound': 'LE'}},
             85: {'customer_address': {'ca_country': 'EQ', 'ca_state': 'EQ'},
                  'customer_demographics': {'cd_education_status': 'EQ', 'cd_marital_status': 'EQ'},
                  'date_dim': {'d_year': 'EQ'},
                  'reason': {'r_reason_desc': 'GB'},
                  'web_returns': {'wr_fee': 'PL', 'wr_refunded_cash': 'PL', 'wr_refunded_cdemo_sk': 'GB'},
                  'web_sales': {'ws_net_profit': 'GE', 'ws_quantity': 'PL', 'ws_sales_price': 'GE'}},
             86: {'date_dim': {'d_month_seq': 'GE'}, 'item': {'i_category': 'GB', 'i_class': 'GB'}},
             87: {'date_dim': {'d_month_seq': 'GE'}},
             88: {'household_demographics': {'hd_dep_count': 'EQ', 'hd_vehicle_count': 'LE'},
                  'store': {'s_store_name': 'EQ'},
                  'time_dim': {'t_hour': 'EQ', 't_minute': 'GE'}},
             89: {'date_dim': {'d_date_sk': 'PL', 'd_moy': 'PL', 'd_year': 'EQ'},
                  'item': {'i_brand': 'OB', 'i_category': 'EQ', 'i_class': 'EQ', 'i_item_sk': 'PL'},
                  'store': {'s_company_name': 'OB', 's_store_name': 'OB'}},
             90: {'household_demographics': {'hd_dep_count': 'EQ'},
                  'time_dim': {'t_hour': 'GE'},
                  'web_page': {'wp_char_count': 'GE'}},
             91: {'call_center': {'cc_call_center_id': 'GB', 'cc_manager': 'GB', 'cc_name': 'GB'},
                  'catalog_returns': {'cr_net_loss': 'PL'},
                  'customer_address': {'ca_gmt_offset': 'EQ'},
                  'customer_demographics': {'cd_education_status': 'EQ', 'cd_marital_status': 'EQ'},
                  'date_dim': {'d_moy': 'EQ', 'd_year': 'EQ'},
                  'household_demographics': {'hd_buy_potential': 'like'}},
             92: {'item': {'i_manufact_id': 'EQ'}, 'web_sales': {'ws_ext_discount_amt': 'GT', 'ws_item_sk': 'GB'}},
             93: {'reason': {'r_reason_desc': 'EQ'},
                  'store_returns': {'sr_return_quantity': 'PL'},
                  'store_sales': {'ss_customer_sk': 'OB', 'ss_quantity': 'PL', 'ss_sales_price': 'PL'}},
             94: {'customer_address': {'ca_state': 'EQ'},
                  'web_sales': {'ws_ext_ship_cost': 'PL',
                                'ws_net_profit': 'PL',
                                'ws_order_number': 'GB',
                                'ws_warehouse_sk': 'PL'},
                  'web_site': {'web_company_name': 'EQ'}},
             95: {'customer_address': {'ca_state': 'EQ'},
                  'web_sales': {'ws_ext_ship_cost': 'PL',
                                'ws_item_sk': 'OB',
                                'ws_net_profit': 'PL',
                                'ws_order_number': 'GB'},
                  'web_site': {'web_company_name': 'EQ'}},
             96: {'household_demographics': {'hd_dep_count': 'EQ'},
                  'store': {'s_store_name': 'EQ'},
                  'time_dim': {'t_hour': 'EQ', 't_minute': 'GE'}},
             97: {'date_dim': {'d_month_seq': 'GE'}},
             98: {'item': {'i_category': 'EQ',
                           'i_class': 'GB',
                           'i_current_price': 'GB',
                           'i_item_desc': 'GB',
                           'i_item_id': 'GB'}},
             99: {'call_center': {'cc_name': 'GB'},
                  'catalog_sales': {'cs_sold_date_sk': 'PL'},
                  'date_dim': {'d_month_seq': 'GE'},
                  'ship_mode': {'sm_type': 'GB'},
                  'warehouse': {'w_warehouse_name': 'PL'}}},
 'tables': {1: ['store_returns', 'customer', 'date_dim', 'store'],
            2: ['catalog_sales', 'web_sales', 'date_dim'],
            3: ['date_dim', 'item'],
            4: ['store_sales', 'catalog_sales', 'web_sales', 'customer', 'date_dim'],
            5: ['store_sales',
                'catalog_sales',
                'web_sales',
                'store_returns',
                'catalog_returns',
                'web_returns',
                'catalog_page',
                'web_site',
                'store'],
            6: ['customer', 'date_dim', 'customer_address', 'item'],
            7: ['store_sales', 'customer_demographics', 'date_dim', 'item', 'promotion'],
            8: ['store_sales', 'customer', 'date_dim', 'customer_address', 'store'],
            9: ['store_sales'],
            10: ['catalog_sales', 'web_sales', 'customer', 'customer_demographics', 'date_dim', 'customer_address'],
            11: ['store_sales', 'web_sales', 'customer', 'date_dim'],
            12: ['web_sales', 'item'],
            13: ['store_sales',
                 'customer_demographics',
                 'date_dim',
                 'customer_address',
                 'household_demographics',
                 'store'],
            14: ['store_sales', 'catalog_sales', 'web_sales', 'date_dim', 'item'],
            15: ['catalog_sales', 'customer', 'date_dim', 'customer_address'],
            16: ['catalog_sales', 'catalog_returns', 'customer_address', 'call_center'],
            17: ['store_sales', 'catalog_sales', 'store_returns', 'date_dim', 'item', 'store'],
            18: ['catalog_sales', 'customer', 'customer_demographics', 'date_dim', 'customer_address', 'item'],
            19: ['customer', 'date_dim', 'customer_address', 'item', 'store'],
            20: ['catalog_sales', 'item'],
            21: ['inventory', 'item', 'warehouse'],
            22: ['inventory', 'date_dim', 'item'],
            23: ['store_sales', 'date_dim', 'item'],
            24: ['store_sales', 'customer', 'customer_address', 'item', 'store'],
            25: ['store_sales', 'catalog_sales', 'store_returns', 'date_dim', 'item', 'store'],
            26: ['catalog_sales', 'customer_demographics', 'date_dim', 'item', 'promotion'],
            27: ['store_sales', 'customer_demographics', 'date_dim', 'item', 'store'],
            28: ['store_sales'],
            29: ['store_sales', 'catalog_sales', 'store_returns', 'date_dim', 'item', 'store'],
            30: ['web_returns', 'customer', 'date_dim', 'customer_address'],
            31: ['web_sales', 'date_dim', 'customer_address'],
            32: ['catalog_sales', 'item'],
            33: ['catalog_sales', 'web_sales', 'date_dim', 'customer_address', 'item'],
            34: ['store_sales', 'customer', 'date_dim', 'household_demographics', 'store'],
            35: ['catalog_sales', 'web_sales', 'customer', 'customer_demographics', 'date_dim', 'customer_address'],
            36: ['store_sales', 'date_dim', 'item', 'store'],
            37: ['catalog_sales', 'inventory', 'item'],
            38: ['catalog_sales', 'web_sales', 'customer', 'date_dim'],
            39: ['inventory', 'date_dim', 'item', 'warehouse'],
            40: ['catalog_sales', 'catalog_returns', 'item', 'warehouse'],
            41: ['item'],
            42: ['date_dim', 'item'],
            43: ['store_sales', 'date_dim', 'store'],
            44: ['store_sales'],
            45: ['web_sales', 'customer', 'date_dim', 'customer_address', 'item'],
            46: ['store_sales', 'customer', 'date_dim', 'customer_address', 'household_demographics', 'store'],
            47: ['store_sales', 'date_dim', 'item', 'store'],
            48: ['store_sales', 'customer_demographics', 'date_dim', 'customer_address', 'store'],
            49: ['store_sales',
                 'catalog_sales',
                 'web_sales',
                 'store_returns',
                 'catalog_returns',
                 'web_returns',
                 'date_dim'],
            50: ['store_returns', 'date_dim', 'store'],
            51: ['store_sales', 'web_sales', 'date_dim'],
            52: ['date_dim', 'item'],
            53: ['date_dim', 'item', 'store'],
            54: ['customer', 'date_dim', 'customer_address', 'item', 'store'],
            55: ['date_dim', 'item'],
            56: ['catalog_sales', 'date_dim', 'customer_address', 'item'],
            57: ['catalog_sales', 'date_dim', 'item', 'call_center'],
            58: ['catalog_sales', 'item'],
            59: ['store_sales', 'date_dim', 'store'],
            60: ['catalog_sales', 'web_sales', 'date_dim', 'customer_address', 'item'],
            61: ['store_sales', 'customer', 'date_dim', 'customer_address', 'item', 'promotion', 'store'],
            62: ['web_sales', 'date_dim', 'web_site', 'ship_mode', 'warehouse'],
            63: ['date_dim', 'item', 'store'],
            64: ['catalog_sales',
                 'store_returns',
                 'catalog_returns',
                 'customer',
                 'customer_demographics',
                 'date_dim',
                 'customer_address',
                 'item',
                 'household_demographics',
                 'promotion',
                 'income_band',
                 'store'],
            65: ['store_sales', 'date_dim', 'item', 'store'],
            66: ['catalog_sales', 'time_dim', 'date_dim', 'ship_mode', 'warehouse'],
            67: ['store_sales', 'date_dim', 'item', 'store'],
            68: ['store_sales', 'customer', 'date_dim', 'household_demographics', 'store'],
            69: ['catalog_sales', 'web_sales', 'customer', 'customer_demographics', 'date_dim', 'customer_address'],
            70: ['store_sales', 'date_dim', 'store'],
            71: ['store_sales', 'catalog_sales', 'web_sales', 'time_dim', 'date_dim', 'item'],
            72: ['catalog_sales', 'inventory', 'customer_demographics', 'date_dim', 'item', 'promotion', 'warehouse'],
            73: ['customer', 'date_dim', 'household_demographics', 'store'],
            74: ['store_sales', 'web_sales', 'customer', 'date_dim'],
            75: ['store_sales', 'catalog_sales', 'store_returns', 'catalog_returns', 'web_returns', 'date_dim', 'item'],
            76: ['store_sales', 'catalog_sales', 'web_sales', 'date_dim', 'item'],
            77: ['store_sales',
                 'catalog_sales',
                 'web_sales',
                 'store_returns',
                 'catalog_returns',
                 'web_returns',
                 'web_page',
                 'store'],
            78: ['store_sales',
                 'catalog_sales',
                 'web_sales',
                 'store_returns',
                 'catalog_returns',
                 'web_returns',
                 'date_dim'],
            79: ['store_sales', 'customer', 'date_dim', 'household_demographics', 'store'],
            80: ['catalog_sales',
                 'store_returns',
                 'catalog_returns',
                 'web_returns',
                 'item',
                 'catalog_page',
                 'promotion',
                 'web_site',
                 'store'],
            81: ['catalog_returns', 'customer', 'date_dim', 'customer_address'],
            82: ['inventory', 'item'],
            83: ['store_returns', 'catalog_returns', 'web_returns', 'item'],
            84: ['store_returns', 'customer', 'customer_demographics', 'household_demographics', 'income_band'],
            85: ['web_sales',
                 'web_returns',
                 'customer_demographics',
                 'date_dim',
                 'customer_address',
                 'web_page',
                 'reason'],
            86: ['date_dim', 'item'],
            87: ['catalog_sales', 'web_sales', 'date_dim'],
            88: ['store_sales', 'time_dim', 'household_demographics', 'store'],
            89: ['date_dim', 'item', 'store'],
            90: ['web_sales', 'time_dim', 'household_demographics', 'web_page'],
            91: ['catalog_returns',
                 'customer',
                 'customer_demographics',
                 'date_dim',
                 'customer_address',
                 'household_demographics',
                 'call_center'],
            92: ['web_sales', 'item'],
            93: ['store_sales', 'store_returns', 'reason'],
            94: ['web_sales', 'web_returns', 'customer_address', 'web_site'],
            95: ['web_sales', 'web_returns', 'customer_address', 'web_site'],
            96: ['store_sales', 'time_dim', 'household_demographics', 'store'],
            97: ['catalog_sales', 'date_dim'],
            98: ['item'],
            99: ['catalog_sales', 'date_dim', 'ship_mode', 'call_center', 'warehouse']},
        'gb_payload': {1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 7: {}, 8: {}, 9: {}, 10: {}, 11: {},
                       12: {}, 13: {}, 14: {}, 15: {}, 16: {}, 17: {}, 18: {}, 19: {}, 20: {}, 21: {},
                       22: {}, 23: {}, 24: {}, 25: {}, 26: {}, 27: {}, 28: {}, 29: {}, 30: {}, 31: {},
                       32: {}, 33: {}, 34: {}, 35: {}, 36: {}, 37: {}, 38: {}, 39: {}, 40: {}, 41: {},
                       42: {}, 43: {}, 44: {}, 45: {}, 46: {}, 47: {}, 48: {}, 49: {}, 50: {}, 51: {},
                       52: {}, 53: {}, 54: {}, 55: {}, 56: {}, 57: {}, 58: {}, 59: {}, 60: {}, 61: {},
                       62: {}, 63: {}, 64: {}, 65: {}, 66: {}, 67: {}, 68: {}, 69: {}, 70: {}, 71: {},
                       72: {}, 73: {}, 74: {}, 75: {}, 76: {}, 77: {}, 78: {}, 79: {}, 80: {}, 81: {},
                       82: {}, 83: {}, 84: {}, 85: {}, 86: {}, 87: {}, 88: {}, 89: {}, 90: {}, 91: {},
                       92: {}, 93: {}, 94: {}, 95: {}, 96: {}, 97: {}, 98: {}, 99: {}},
        'dim_tables': {}}
